[package]
name = "catppuccin"
version = "0.1.0"
compiler = "0.10.0"
entrypoint = "src/lib.typ"
repository = "https://github.com/TimeTravelPenguin/catppuccin-typst"
authors = [
  "TimeTravelPenguin <35803538+TimeTravelPenguin@users.noreply.github.com>",
]
license = "MIT"
description = "âœ¨ Soothing pastel theme for Typst"
keywords = ["catppuccin", "themes"]
categories = ["fun", "text"]
disciplines = ["mathematics"]

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = "thumbnail.png"
