blank_issues_enabled: false
contact_links:
  - name: Ask A Question
    url: https://github.com/catppuccin/typst/discussions/new?category=q-a
    about: Need help using Catppuccin Typst? Ask questions in GitHub Discussions!
  - name: Show & Tell
    url: https://github.com/catppuccin/typst/discussions/new?category=show-tell
    about: Want to showcase your Catppuccin Typst work? Show it off in GitHub Discussions!
  - name: Community Discord
    url: https://discord.com/servers/catppuccin-907385605422448742
    about: Chat with other community members!
